# -*- coding: utf-8 -*-
"""Mohammed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102FTezFH9qk1-iCIpLy937kGJgKLWql3
"""

# Simplified Reservation class with constructor, attributes, and getter/setter methods
class Reservation:
    def __init__(self, reservation_id, check_in_date, check_out_date, num_of_nights, room_type, status="Confirmed"):
        # Initialize reservation details
        self._reservation_id = reservation_id
        self._check_in_date = check_in_date
        self._check_out_date = check_out_date
        self._num_of_nights = num_of_nights
        self._room_type = room_type

    # Getters
    def get_reservation_id(self):
        return self._reservation_id

    def get_check_in_date(self):
        return self._check_in_date

    def get_check_out_date(self):
        return self._check_out_date

    def get_num_of_nights(self):
        return self._num_of_nights

    def get_room_type(self):
        return self._room_type

    # Setters
    def set_reservation_id(self, reservation_id):
        self._reservation_id = reservation_id

    def set_check_in_date(self, check_in_date):
        self._check_in_date = check_in_date

    def set_check_out_date(self, check_out_date):
        self._check_out_date = check_out_date

    def set_num_of_nights(self, num_of_nights):
        self._num_of_nights = num_of_nights

    def set_room_type(self, room_type):
        self._room_type = room_type

# Simplified Customer class with constructor, attributes, and getter/setter methods
class Customer:
    def __init__(self, name, email, phone, payment_method, credit_card, loyalty_points=0):
        # Initialize customer details
        self._name = name
        self._email = email
        self._phone = phone
        self._payment_method = payment_method
        self._credit_card = credit_card

    # Getters
    def get_name(self):
        return self._name

    def get_email(self):
        return self._email

    def get_phone(self):
        return self._phone

    def get_payment_method(self):
        return self._payment_method

    def get_credit_card(self):
        return self._credit_card

    # Setters
    def set_name(self, name):
        self._name = name

    def set_email(self, email):
        self._email = email

    def set_phone(self, phone):
        self._phone = phone

    def set_payment_method(self, payment_method):
        self._payment_method = payment_method

    def set_credit_card(self, credit_card):
        self._credit_card = credit_card

# Simplified Room class with constructor, attributes, and getter/setter methods
class Room:
    def __init__(self, room_number, room_type, price_per_night, availability, floor_number):
        # Initialize room details
        self._room_number = room_number
        self._room_type = room_type
        self._price_per_night = price_per_night
        self._availability = availability
        self._floor_number = floor_number

    # Getters
    def get_room_number(self):
        return self._room_number

    def get_room_type(self):
        return self._room_type

    def get_price_per_night(self):
        return self._price_per_night

    def get_availability(self):
        return self._availability

    def get_floor_number(self):
        return self._floor_number

    # Setters
    def set_room_number(self, room_number):
        self._room_number = room_number

    def set_room_type(self, room_type):
        self._room_type = room_type

    def set_price_per_night(self, price_per_night):
        self._price_per_night = price_per_night

    def set_availability(self, availability):
        self._availability = availability

    def set_floor_number(self, floor_number):
        self._floor_number = floor_number

# Simplified Payment class with constructor, attributes, and getter/setter methods
class Payment:
    def __init__(self, payment_id, total_amount, payment_method, payment_date="2024-10-01", currency="USD"):
        # Initialize payment details
        self._payment_id = payment_id
        self._total_amount = total_amount
        self._payment_method = payment_method
        self._payment_date = payment_date
        self._currency = currency

    # Getters
    def get_payment_id(self):
        return self._payment_id

    def get_total_amount(self):
        return self._total_amount

    def get_payment_method(self):
        return self._payment_method

    def get_payment_date(self):
        return self._payment_date

    def get_currency(self):
        return self._currency

    # Setters
    def set_payment_id(self, payment_id):
        self._payment_id = payment_id

    def set_total_amount(self, total_amount):
        self._total_amount = total_amount

    def set_payment_method(self, payment_method):
        self._payment_method = payment_method

    def set_payment_date(self, payment_date):
        self._payment_date = payment_date

    def set_currency(self, currency):
        self._currency = currency

# Simplified Hotel class with constructor, attributes, and getter/setter methods
class Hotel:
    def __init__(self, name, address, city, state, zip_code, phone, rating=4):
        # Initialize hotel details
        self._name = name
        self._address = address
        self._city = city
        self._state = state
        self._zip_code = zip_code
        self._phone = phone

    # Getters
    def get_name(self):
        return self._name

    def get_address(self):
        return self._address

    def get_city(self):
        return self._city

    def get_state(self):
        return self._state

    def get_zip_code(self):
        return self._zip_code

    def get_phone(self):
        return self._phone

    # Setters
    def set_name(self, name):
        self._name = name

    def set_address(self, address):
        self._address = address

    def set_city(self, city):
        self._city = city

    def set_state(self, state):
        self._state = state

    def set_zip_code(self, zip_code):
        self._zip_code = zip_code

    def set_phone(self, phone):
        self._phone = phone


# Function to print receipt details
def print_receipt(customer, reservation, room, payment, hotel):
    print("+" * 90)
    print("Your Reservation is Confirmed")
    print("Thank you for your reservation. Please print your hotel receipt and show it at check-in.")

    # Print customer details
    print("Your Name: " + customer.get_name())
    print("Your Email: " + customer.get_email())

    # Print reservation details
    print("Priceline Trip Number: " + reservation.get_reservation_id())
    print("Hotel Confirmation Number: " + room.get_room_number())
    print("-" * 90)

    # Print hotel details
    print(hotel.get_name())
    print(hotel.get_address())
    print(hotel.get_city() + ", " + hotel.get_state() + " " + hotel.get_zip_code())
    print("Phone: " + hotel.get_phone())
    print("~" * 90)

    # Print check-in and check-out details
    print("Check-In: " + reservation.get_check_in_date() + " - 03:00 PM")
    print("Check-Out: " + reservation.get_check_out_date() + " - 12:00 PM")
    print("Number of Nights: " + str(reservation.get_num_of_nights()))
    print("Number of Rooms: 1")
    print("#" * 90)

    # Print room details
    print("Room 1: " + customer.get_name())
    print("Room Type: " + room.get_room_type())
    print("Room Floor number: " + room.get_floor_number())
    print("^" * 90)

    # Print summary of charges
    print("Summary of Charges")
    print("Billing Name:         " + customer.get_name())
    print("Credit Card:          " + customer.get_payment_method() + " (ending in " + customer.get_credit_card() + ")")
    print("Room Cost:            $" + str(room.get_price_per_night()))
    print("avg per room per night")
    print("Rooms:                1")
    print("Nights:               " + str(reservation.get_num_of_nights()))

    # Calculate and print subtotal and fees
    subtotal = room.get_price_per_night() * reservation.get_num_of_nights()
    print("Room Subtotal:        $" + str(subtotal))

    taxes_and_fees = payment.get_total_amount() - subtotal
    print("Taxes and Fees:       $" + str(taxes_and_fees))
    print("Total Charges:        $" + str(payment.get_total_amount()) + " " + payment.get_currency())
    print("prices are in US dollars")
    print("*" * 90)

# Create objects and populate data
customer1 = Customer("Ted Vera", "tedvera@mac.com", "123456789", "Mastercard", "1904")
reservation1 = Reservation("15549850358", "Sun, Aug 22, 2010", "Tue, Aug 24, 2010", 2, "2 Queen Beds No Smoking")
room1 = Room("52523687", "2 Queen Beds No Smoking Desk/Safe/Coffee Maker in Room/Hair Dryer", 89.95, True, "5")
payment1 = Payment("2010-08-22", 201.48, "Mastercard", "2024-10-01", "USD")
hotel1 = Hotel("Comfort Inn & Suites Los Alamos", "2455 Trinity Drive", "Los Alamos", "NM", "87544", "505-661-1110", 4)

# Print the first receipt
print_receipt(customer1, reservation1, room1, payment1, hotel1)
print()

# Create a second set of objects and populate data
customer2 = Customer("Mohammed", "Mohammed@live.com", "987654321", "Visa", "3721")
reservation2 = Reservation("89451287950", "Mon, Sep 13, 2024", "Wed, Sep 15, 2024", 3, "1 King Bed Suite")
room2 = Room("87452309", "1 King Bed Suite with Balcony and Ocean View", 120.75, True, "8")
payment2 = Payment("2024-09-13", 400.25, "Visa", "2024-10-01", "USD")
hotel2 = Hotel("Sunset Resort", "1234 Pine Anenue", "Dubai Beach", "UAE", "33139", "305-555-1234", 5)

# Print the second receipt
print_receipt(customer2, reservation2, room2, payment2, hotel2)
print()

# Create a third set of objects and populate data
customer3 = Customer("Alia", "alia@gmail.com", "654987321", "Abu DHabi Express", "8745")
reservation3 = Reservation("41258963214", "Fri, Jul 16, 2024", "Sun, Jul 18, 2024", 2, "Standard Room")
room3 = Room("36985214", "Standard Room with Garden View", 75.50, True, "3")
payment3 = Payment("2024-07-16", 176.50, "Abu Dhabi Express", "2024-10-01", "AED")
hotel3 = Hotel("Green Valley Hotel", "789 Hillside Dr", "Abu DHabi", "UAE", "80203", "303-555-7890", 3)

print()
# Print the third receipt
print_receipt(customer3, reservation3, room3, payment3, hotel3)

